2019-11-05 18:25:43,005 ERROR: Exception on /auth/login [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/nea_project_bp/app/auth/routes.py", line 25, in login
    return render_template('auth/login.html', title='Login', form=form)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/nea_project_bp/app/templates/auth/login.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/nea_project_bp/app/templates/auth/login.html", line 17, in root
    </center>
  File "/home/ubuntu/nea_project_bp/app/templates/base.html", line 14, in root
    <!-- Custom CSS, JS & Favicon (Including FontAwesome) -->
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/ubuntu/nea_project_bp/app/templates/auth/login.html", line 30, in block_content
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/ubuntu/.local/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2019-11-05 18:27:19,630 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 18:27:21,916 ERROR: Exception on / [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_login/utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/ubuntu/.local/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2019-11-05 18:33:18,326 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:09:19,981 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:10:21,602 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:13:18,081 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:14:38,807 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:17:12,903 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:18:02,392 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:18:35,073 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:19:02,168 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:19:27,793 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:25:22,682 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:26:14,789 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:26:38,576 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:27:16,509 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:27:34,191 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:28:28,888 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:30:11,070 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:30:37,898 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:31:04,883 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:31:34,569 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:53]
2019-11-05 20:42:09,787 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:56]
2019-11-06 11:50:49,373 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:56]
2019-11-06 11:56:06,606 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:56]
2019-11-06 12:05:48,372 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:56]
2019-11-06 19:38:17,976 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:56]
2019-11-06 19:40:31,192 INFO: WYJP startup [in /home/ubuntu/nea_project_bp/app/__init__.py:56]
