2019-11-11 16:59:29,269 ERROR: Exception on /live_timetable [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/nea_project/app/main/routes.py", line 75, in stops
    locality=locality, stop_number_str=stop_number_str) #, location=location)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/nea_project/app/templates/live_timetable.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/nea_project/app/templates/live_timetable.html", line 17, in root
    <thead>
  File "/home/ubuntu/nea_project/app/templates/base.html", line 14, in root
    <!-- Custom CSS, JS & Favicon (Including FontAwesome) -->
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 90, in block_body
  File "/home/ubuntu/nea_project/app/templates/base.html", line 66, in block_navbar
    {% endblock %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/ubuntu/.local/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'file_handling.downloadspage'. Did you mean 'file_handlers.downloadspage' instead?
2019-11-11 16:59:51,579 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:11:48,510 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:11:57,641 ERROR: Exception on /downloads [GET] [in /home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/nea_project/app/file_handlers/downloads.py", line 10, in downloadspage
    return render_template('downloads.html', title='Downloads')
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/nea_project/app/templates/downloads.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/ubuntu/nea_project/app/templates/downloads.html", line 14, in root
    </div>
  File "/home/ubuntu/nea_project/app/templates/base.html", line 14, in root
    <!-- Custom CSS, JS & Favicon (Including FontAwesome) -->
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/ubuntu/nea_project/app/templates/downloads.html", line 23, in block_content
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/ubuntu/.local/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'download_timetables'. Did you mean 'file_handlers.download_timetables' instead?
2019-11-11 17:17:29,396 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:18:19,978 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:18:20,812 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:19:33,602 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:20:13,273 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:20:27,477 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:20:49,068 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:20:49,889 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:22:21,680 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:22:22,669 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:24:43,566 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:24:44,381 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:25:36,982 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:26:23,969 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:26:36,766 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:26:46,385 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
2019-11-11 17:27:38,797 INFO: WYJP startup [in /home/ubuntu/nea_project/app/__init__.py:59]
